# IoT Device Simulator based on Node-RED with FIWARE integration
version: '3'

services:
  node-red:
    build:
      context: .
      dockerfile: docker/node-red/Dockerfile
    ports:
      - "1880:1880"
    environment:
      - TZ=Asia/Tokyo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1880"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - fiware_network

  orion:
    image: fiware/orion:3.10.1
    ports:
      - "1026:1026"
    command: -dbhost mongodb
    depends_on:
      - mongodb
    networks:
      - fiware_network

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fiware_network

networks:
  fiware_network:
    driver: bridge

volumes:
  mongodb_data:
